name: spacex_rockets
description: A Flutter app to display SpaceX rockets and their details.
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0

  # Networking
  dio: ^5.4.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.0.1
  json_annotation: ^4.8.1

  # Local Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.2

  # Image Handling
  cached_network_image: ^3.3.0

  # URL Launcher
  url_launcher: ^6.2.5

  # Utility
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^8.0.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true
